version: 2

project_name: furit
builds:
  - main: .
    binary: furit
    # refer to the https://pkg.go.dev/cmd/link
    ldflags:
      - -s -w -X main.Revision={{.ShortCommit}}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm64
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE
release:
  prerelease: auto

brews:
  - repository:
      owner: kemokemo
      name: homebrew-tap
    homepage: "https://github.com/kemokemo/furit"
    description: "This tool finds unreferenced images from text files such as markdown."
    install: |
      bin.install "furit"
scoops:
  - repository:
      owner: kemokemo
      name: scoop-bucket
    homepage:  https://github.com/kemokemo/furit
    description: This tool finds unreferenced images from text files such as markdown. 
    license: MIT
